# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=9)),
                ('student_class', models.CharField(max_length=30)),
                ('ac_times', models.IntegerField(default=0)),
                ('submit_times', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
